In [1]:
# pip install numpy
import numpy as np

In [4]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
np.zeros((5,7,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [6]:
np.zeros((1))

array([0.])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
np.arange(4,20) #intervalos abiertos e cerrados# [4, 20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(-12,1) 

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [19]:
np.arange(0,20,2) 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.arange(-12,0,0.5) 

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5])

In [24]:
areglo_pares=np.arange(0,20,2) 


In [27]:
print(areglo_pares.size)
print(len(areglo_pares))
areglo_tres_dimensiones=np.zeros((2,3,4))
print(areglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [28]:
areglo_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
areglo_pares.shape # para ver las dimensiones

(10,)

In [31]:
areglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [32]:
areglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [33]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
arreglo_elemento=np.arange(24)

In [35]:
arreglo_elemento.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [36]:
arreglo_elemento.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [37]:
arreglo_elemento.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [38]:
arreglo_elemento.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
arreglo_elemento.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [40]:
arreglo_elemento.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [41]:
arreglo_elemento.reshape(1,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [42]:
arreglo_elemento.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [43]:
arreglo_elemento.reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [45]:
arreglo_elemento.reshape(2,1,12)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]])

In [46]:
arreglo_elemento.reshape(1,8,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [47]:
arreglo_elemento.reshape(12,1,2).reshape

array([[[ 0,  1]],

       [[ 2,  3]],

       [[ 4,  5]],

       [[ 6,  7]],

       [[ 8,  9]],

       [[10, 11]],

       [[12, 13]],

       [[14, 15]],

       [[16, 17]],

       [[18, 19]],

       [[20, 21]],

       [[22, 23]]])

In [48]:
arreglo_elemento.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [49]:
a=np.array([10,10,10])
b=np.array([5,5,5])
a+b

array([15, 15, 15])

In [50]:
#Restas
a-b

array([5, 5, 5])

In [51]:
#multiplicaciones
a*b

array([50, 50, 50])

In [52]:
#divisiones
a/b

array([2., 2., 2.])

In [75]:
#3 dimenciones 
arreglo_tres_dimensiones1=np.arange(20).reshape(2,3,4)
print(arreglo_tres_dimensiones1)

[2 3 4]


In [85]:
arreglo_tres_dimensiones2=np.arange(20).reshape(2,3,4)
arreglo_tres_dimensiones2

ValueError: cannot reshape array of size 20 into shape (2,3,4)

In [62]:
print(suma)

[0 2 4]


In [71]:
#Mod
a%b

array([0, 0, 0], dtype=int32)

In [73]:
a%b

array([0, 0, 0], dtype=int32)

In [81]:
#Multiplicar
print(a*10)
#Mod
print (a%3)
#resta
print(a-10)

[100 100 100]
[1 1 1]
[0 0 0]


In [82]:
arreglo_muestra=np.arange(20).reshape(5,2,2)

In [83]:
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [122]:

resp = (arreglo_muestra > 5) & (arreglo_muestra < 12)
arreglo_muestra[resp]


TypeError: '>' not supported between instances of 'list' and 'int'

In [123]:
A= np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [90]:
arreglo_muestra[resp]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [94]:
arreglo_muestra[resp]


array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False])

In [124]:
A= np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [125]:
B= np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [126]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [127]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [128]:
##Producto punto 
B.dot(A)

array([[10, 19],
       [14, 27]])

In [129]:
arreglo_doce= np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [130]:
arreglo_doce.sum()

66

In [131]:
arreglo_doce.min()

0

In [132]:
arreglo_doce.max()

11

In [135]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [136]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [137]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

In [138]:
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
#axis suma de la alto largo ancho 
#Se tiene tres dimenciones x,y,z en x se toma en cuenta su posicion, axis=0 en la posicion 0
#en x axis =1 se toma en cuenta la suma vertical, en y axis=2 la suma de  manera horizontal.
#Proyectando un cudo.